### ISSUE TITLE
 fix enum handling

### ISSUE THREAD

**Issue by erlanggadewa** [Brakebein/prisma-generator-nestjs-dto#1]
@Brakebein your repo is great, but I need enum handler error and your repo not implement it yet. Maybe you can use @IsEnum class validator for enum handling error

**Comment by Brakebein** [comment]
Thanks. `enum` handling is on my list, but I didn't find time yet to implement it. I can maybe do it until the end of August.

Maybe you can use `@IsIn(values: any[])` as a workaround?

**Comment by erlanggadewa** [comment]
Thanks for your advice, I have a lot field working using enum and it will take time if i do  manually. But no problem , I will waiting you for implement it. Thanks
