### ISSUE TITLE
Generated connect or create classes get too many suffices

### ISSUE THREAD

**Issue by zackdotcomputer** [Brakebein/prisma-generator-nestjs-dto#17]
I have the schema set to configure both:
```
dtoSuffix                     = "DtoAttributes"
entitySuffix                  = "Attributes"
```

However, when I annotate something with `@DtoRelationCanCreateOnCreate` or `@DtoRelationCanConnectOnCreate` then the interface for the connect or create generates with the `dtoSuffix` but the property itself receives both suffices:

```typescript
interface CreateOfferAttachmentsRelationInputDtoAttributes {
  create: CreateOfferAttachmentDtoAttributes[];
}

export interface CreateOfferDtoAttributes {
  candidateName: string;
  candidatePosition: string;
  attachments?: CreateOfferAttachmentsRelationInputDtoAttributesAttributes;
}
```

This fails compile because the type does not exist.

I tried to look into this and traced that the second suffix is being added some time after `helpers.ts` returns the value, since `type` there is correct. I can't figure out where this is happening, though, or what the potential follow-on risks would be to changing this.

**Comment by Brakebein** [comment]
Thanks! There is a small check if the dto or entity class name should be generated and it only checked if the provided name ends with `dto`. So if the `dtoSuffix` ends with `dto` everything went fine. Now, this check considers the whole `dtoSuffix` (see commit).

I just released version 1.17.4
