### ISSUE TITLE
Feature request @ApiHideProperty

### ISSUE THREAD

**Issue by okonon** [Brakebein/prisma-generator-nestjs-dto#23]
I am willing to contribute my work around supporting @ApiHideProperty annotation of the  `@nestjs/swagger` package. I have a working hack and looking for guidance and gotchas before i create a PR. Is there anything to watch out for ?

**Comment by Brakebein** [comment]
What is the actual use case of @ApiHideProperty? So, in contrast to `@DtoReadOnly`, the property would still be in the dtos, but it should not be part of the swagger documentation?

Taking the example field `name String`, it would normally generate:
```ts
@ApiProperty()
@IsNotEmpty()
@IsString()
name: string;
```
With @ApiHideProperty it should generate:
```ts
@ApiHideProperty()
@IsNotEmpty()
@IsString()
name: string;
```
or can it be just:
```ts
@IsNotEmpty()
@IsString()
name: string;
```
?

And what is your working hack so far?

**Comment by okonon** [comment]
@Brakebein thanks for your reply and sorry for the delay. Basically i ran into a problem where i needed to access DB audit fields like `createdAt`, `updatedAt`, `createdBy`, and `updatedBy` in DTOs but wanted to hide them from Swagger exactly like you said. and the hack to work around is the code that would handle `/// @ApiHideProperty true`

**Comment by Brakebein** [comment]
Now, I finally implemented it. By adding `/// @DtoApiHidden`, it will add `@ApiHideProperty()` to a field instead of `@ApiProperty()`.

Please check and test: https://www.npmjs.com/package/@brakebein/prisma-generator-nestjs-dto/v/1.18.0-beta3

**Comment by okonon** [comment]
@Brakebein thanks a lot tested it and it works perfectly!
