### ISSUE TITLE
Support for conditional validation by class-validator

### ISSUE THREAD

**Issue by iamciroja** [Brakebein/prisma-generator-nestjs-dto#37]
Current version of generator allows us to use validation decorators from class-validator. But it seems that [conditional validation](https://github.com/typestack/class-validator#conditional-validation) feature is not supported yet. Also I suppose that these conditions may differ in Create and Update DTOs.

One of the possible solutions is to add a couple of new decorators - @DtoCreateValidateIf(...) and @DtoUpdateValidateIf(...) - which will be transformed to @ValidateIf() decorator in corresponding DTO

[This pull request](https://github.com/Brakebein/prisma-generator-nestjs-dto/pull/36) add this functionality

**Comment by Brakebein** [comment]
Thanks! I will look into it.

**Comment by Brakebein** [comment]
I just released version [1.20.0](https://www.npmjs.com/package/@brakebein/prisma-generator-nestjs-dto/v/1.20.0) including your changes.
