### ISSUE TITLE
Support Swagger Annotations for nested create

### ISSUE THREAD

**Issue by ChristopherCapito** [Brakebein/prisma-generator-nestjs-dto#4]
Greetings,

first of all: Great work. I really enjoy this generator in conjunction with nest g res and another crud-service generator to bootstrap basic crud functionality quickly.

I noticed that this generator does not include typings for nested writes in Swagger. I guess this makes sense because of the "Create/Connect" DTOs needed. Would it be possible however, to include these as API Properties during generation? This is so we have proper API documentation, should an entity require or allow for nested creation.
An example could be:

1. User Model
2. Media Model

On user creation, you can pass a media array (create or connect eg.).

I hope this was somewhat understandable. :) I would help as this helps me aswell. I have however never contributed anything before and have not worked with generators. How would get started about it? :)

**Comment by Brakebein** [comment]
I don't fully understand your issue and how the expected outcome should look like. Can you please provide a small example including: how does the input model look like (schema.prisma), how should the generated dto files look like?

**Comment by ChristopherCapito** [comment]
Sorry for the late response. I will include an example later today. Great work on this library by the way!
