### ISSUE TITLE
Feature request @DtoUpdateRequired

### ISSUE THREAD

**Issue by KoenLemmen** [Brakebein/prisma-generator-nestjs-dto#40]
Please add a decorator that sets an update DTO property to required: true and no ? and @IsOptional()

For example:
```
  @ApiProperty({
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString()
  name?: string;
```
Would become
```
  @ApiProperty({
    type: 'string',
    required: true, // or if true by default remove this line
  })
  @IsString()
  name: string;
```

Right now I modify this manually locally, but we run prisma generate during CI/CD and this overwrites the manually edited DTO's causing errors.
Please consider this for users who want a property in update to be required for each update.

**Comment by Brakebein** [comment]
Thanks! I just released a new version that includes your additions.

**Comment by KoenLemmen** [comment]
Thanks!
