### ISSUE TITLE
Fields of type String are not getting the @ApiProperty decorator

### ISSUE THREAD

**Issue by mohamedamara1** [Brakebein/prisma-generator-nestjs-dto#47]
Hello, thank you for this package it is very useful.
I noticed that for each field in my schema, the generated DTOs doesn't have the @ApiProperty decorator on the fields that are of String type, am I missing something here?

**Comment by Brakebein** [comment]
Hm, that shouldn't be the case. Can you share some of your schema.prisma (config, one model)?

**Comment by mohamedamara1** [comment]
Thanks for the quick answer,
this is the config
![image](https://github.com/user-attachments/assets/50e6daf1-8174-4341-b7a6-c03c7eba32c4)

 example of a model:
![image](https://github.com/user-attachments/assets/77beb8a0-a05c-43cc-a2ad-98d554b1017f)

this is the generated dto
![image](https://github.com/user-attachments/assets/20336bee-9a69-4eea-893b-57dd0c7fe020)

updateDto
![image](https://github.com/user-attachments/assets/9b2c74a0-9f82-4bf0-b27c-0dec5f0067c1)

it's the same for every other model

**Comment by mohamedamara1** [comment]
My bad I fixed it, it was an issue from my part, there was this line added here
![image](https://github.com/user-attachments/assets/26d332c9-2e10-401b-b342-767eee9c6be7)
of the same package, I'm not sure how it got there..
