### ISSUE TITLE
Disable MTM relations generation in config

### ISSUE THREAD

**Issue by Serpentarius13** [Brakebein/prisma-generator-nestjs-dto#50]
I want to disable generating all MTM relations (and possible all relations whatsoever) in config, rather than writing `/// DtoEntityHidden` on every model. By default Prisma doesn't include those relations in returning records, so I think this feature should be on-demand rather than turned on from the start

**Comment by Brakebein** [comment]
The output without any relations is basically the plain DTO. I recently added the config to omit the generation of entity files; https://github.com/Brakebein/prisma-generator-nestjs-dto/issues/42#issuecomment-2259990757

Does it already solve your issue? Or am I missing something?

**Comment by Serpentarius13** [comment]
> The output without any relations is basically the plain DTO. I recently added the config to omit the generation of entity files; [#42 (comment)](https://github.com/Brakebein/prisma-generator-nestjs-dto/issues/42#issuecomment-2259990757)
> 
> Does it already solve your issue? Or am I missing something?

Yeah, thanks, I think I will just use entities then.
