### ISSUE TITLE
Problems with @description and @example

### ISSUE THREAD

**Issue by tofsjonas** [Brakebein/prisma-generator-nestjs-dto#58]
## @description and @example tags without quotes

This prisma schema:

```prisma
  /// @description 2024-10-24T13:52:23.296Z
  /// @example 2024-10-24T13:52:23.296Z
  expire_at DateTime?
```

generates this code:

```ts
@ApiProperty({
  description: 2024-10-24T13:52:23.296Z,
  example: 2024-10-24T13:52:23.296Z,
  type: 'string',
  format: 'date-time',
  required: false,
  nullable: true,
})
@IsOptional()
@IsDateString()
expire_at?: Date  | null;
```

Which is invalid because the `description` and `example` fields should be strings.

## @description and @example tags with quotes

This prisma schema:

```prisma
  /// @description "2024-10-24T13:52:23.296Z"
  /// @example "2024-10-24T13:52:23.296Z"
  expire_at DateTime?
```

generates this code:

```ts
@ApiProperty({
  description: '"2024-10-24T13:52:23.296Z"',
  example: '"2024-10-24T13:52:23.296Z"',
  type: 'string',
  format: 'date-time',
  required: false,
  nullable: true,
})
@IsOptional()
@IsDateString()
expire_at?: Date  | null;
```

which is valid **code**, but is incorrect because `expire_at` is not a string with quotes. So the swagger becomes invalid.

These work fine:

```prisma
  /// @example M4a8ALOgGuCHuxK
  /// @example +46754489636
```

These fail:

```prisma
  /// @example 9ee102e8-b43a-4a48-9a06-47b059e88137
  /// @example 2024-10-24T13:52:23.296Z
```

## A potential fix

The problem seems to be this function:

```ts
// src/generator/api-decorator.ts
/**
 * Wrap string with single-quotes unless it's a (stringified) number, boolean, or array.
 */
function encapsulateString(value: string): string {
  return /^$|^(?!true$|false$)[^0-9\[]/.test(value)
    ? `'${value.replace(/'/g, "\\'")}'`
    : value;
}
```

And here is a fix:

```ts
// src/generator/api-decorator.ts
/**
 * Wrap string with single-quotes unless it's a (stringified) number, boolean, or array.
 */
function encapsulateString(value: string): string {
  // Don't quote booleans, numbers, or arrays
  if (
    value === 'true' || 
    value === 'false' || 
    /^\d+$/.test(value) ||
    /^\[.*\]$/.test(value)
  ) {
    return value;
  }
  
  // Quote everything else
  return `'${value.replace(/'/g, "\\'")}'`;
}
```

Should I create a PR for this?

**Comment by Brakebein** [comment]
Thanks for the report. Yes, this regular expression is not very robust. It's better to split this test like in your proposed fix. The only problem there is that you don't consider fractional number, e.g. `3.14159`. I will fix it, and also add some tests.

**Comment by tofsjonas** [comment]
Awesome, thanks! 😊

**Comment by Brakebein** [comment]
Fix has been released (v 1.23.3).

**Comment by tofsjonas** [comment]
Er, sorry to be a bother, but could you please include it in the `1.24.0-beta` also? 🙏🥹🤞

**Comment by Brakebein** [comment]
I wanted to release a proper version soon, when I got some feedback on some other features. So, I was doing those quick fixes on the main branch. But here you go: [1.24.0-beta4](https://www.npmjs.com/package/@brakebein/prisma-generator-nestjs-dto/v/1.24.0-beta4)

**Comment by tofsjonas** [comment]
Null! We forgot null!

**Comment by Brakebein** [comment]
You are right! [1.24.0-beta5](https://www.npmjs.com/package/@brakebein/prisma-generator-nestjs-dto/v/1.24.0-beta5)
