### ISSUE TITLE
Permission Denied Error when using the generator in WSL2

### ISSUE THREAD

**Issue by ChristopherCapito** [Brakebein/prisma-generator-nestjs-dto#7]
Greetings.

When using npx prisma generate with your generator activated, I am getting "permission denied" when running in WSL2. 
I am also using the crud generator from prisma-utils, which works just fine. I assume something in the way you are accessing the filesystem produces this error, as other generators I am using do not have this problem.

I, however, don't know where to look :/ - do you have an idea what could be the cause?

System Info:
WSL2 Ubuntu 2004.2022.1.0 on Windows 11
@brakebein/prisma-generator-nestjs-dto": "^1.13.0

for comparison:
@prisma-utils/prisma-crud-generator": "^1.2.9

I hope you can help me out. I tried messing with filesystem permissions, but I am not that proficient in Linux yet

**Comment by ChristopherCapito** [comment]
Hey, just a comment. So I just out of curiosity deleted my node_modules and package-lock.json to revert some NPM upgrades I did a few days ago.

I think the issue might be lying with other dependencies. I will try to bump the dependencies one by one to find out where the incompatibility arises.

**Comment by Brakebein** [comment]
I didn't have any problems yet using the generator in WSL2 on Windows 10.
