### ISSUE TITLE
CRLF line endings cause error on MacOS

### ISSUE THREAD

**Issue by mattrossman** [Brakebein/prisma-generator-nestjs-dto#9]
When installing the latest version of this from NPMJS and using it in my Prisma schema, I get the error `env: node\r: No such file or directory`:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/22670878/203405026-c354f635-2168-4b3b-8879-ce3c35574e42.png">

It looks like the published file (e.g. `dist/cli.js`) uses CRLF endings instead of LF which causes issues outside of Windows. Whereas building it locally with LF endings fixes the error.

It'd be helpful to have this published with LF endings, perhaps automated via [dos2unix](https://www.npmjs.com/package/dos2unix)

**Comment by Brakebein** [comment]
Thanks for reporting. With the newest release, it should now work on all platforms.

**Comment by mattrossman** [comment]
Thank you! I can confirm it works now on Mac
